### ISSUE TITLE
Bug: Machine is set into maintenance but is forgotten in next run

### ISSUE THREAD

**Issue by Wausert** [leeej84/PowerScale#27] opened 2021-01-12 19:07 UTC
Hi, I have an issue which is causing a machine stuck in maintenance mode and shutting down the wrong machine.
Machine XA-Worker-05 was powered up via Powerscale during the day and was set to maintenance mode automatically when the number of sessions dropped during the day. 

Powerscale does not shutdown XA-Worker-05 during the day but keeps the machine in maintenance mode (I prefer to have it shut down if possible). When business ours end and a new run is performed it seems Powerscale does see XA-Worker-05 powered up but chooses to shutdown the active machine with active users (signalling them to logoff) in stead of powering off XA-Worker-05 which has been in maintenance mode all the time and has no sessions active.

I do scaling based on session and business hours. This is in the log:

2021-01-12 18:00:02 INFO: -
2021-01-12 18:00:02 INFO: #######PowerScale script starting - Test mode value is False#######
2021-01-12 18:00:02 INFO: Getting a list of machine from dc01 based on prefix - XA-Worker-0
2021-01-12 18:00:02 INFO: Performance scaling is enabled - attempting performance metrics capture
2021-01-12 18:00:02 INFO: The authentication account provided is in the correct format, continuing
2021-01-12 18:00:02 INFO: Starting performance measurement job for XA-Worker-01 using specified credentials
2021-01-12 18:00:03 INFO: CIM Connection test for XA-Worker-01 successful
2021-01-12 18:00:03 INFO: Starting performance measurement job for XA-Worker-02 using specified credentials
2021-01-12 18:00:03 INFO: CIM Connection test for XA-Worker-02 successful
2021-01-12 18:00:03 INFO: Starting performance measurement job for XA-Worker-03 using specified credentials
2021-01-12 18:00:03 INFO: CIM Connection test for XA-Worker-03 successful
2021-01-12 18:00:03 INFO: Starting performance measurement job for XA-Worker-04 using specified credentials
2021-01-12 18:00:03 INFO: CIM Connection test for XA-Worker-04 successful
2021-01-12 18:00:08 INFO: 4 - Overall CPU Average
2021-01-12 18:00:08 INFO: 28.5 - Overall Memory Average
2021-01-12 18:00:08 INFO: 240 - Overall Session Index Average
2021-01-12 18:00:08 INFO: 5.75 - Overall Session Count Average
2021-01-12 18:00:08 INFO: Start Circular Log Management
2021-01-12 18:00:08 INFO: The current number of powered on machines is 4 and the target is 4 - resulting action is to perform Scaling calculations
2021-01-12 18:00:08 INFO: It is currently inside working hours - performing machine analysis
2021-01-12 18:00:08 INFO: Additional scaling is not enabled, the number of machines to scale at each run will be set to the default of 1
2021-01-12 18:00:08 INFO: The current running machines matches the target machines number, performing scaling analysis
2021-01-12 18:00:08 INFO: Scaling has been selected, the current scaling metric is Session and there are 3 machines currently powered off and there are 1 in maintenance mode available.
2021-01-12 18:00:08 INFO: Working with maintenanceMachines this round - maintenance machines will always be selected first
2021-01-12 18:00:08 INFO: Machine selected to be placed into service is XA-Worker-05 the machine is powered On and maintename mode is True
2021-01-12 18:00:09 INFO: #######PowerScale script finishing####### 

Next run:

2021-01-12 19:30:02 INFO: #######PowerScale script starting - Test mode value is False#######
2021-01-12 19:30:02 INFO: Getting a list of machine from dc01 based on prefix - XA-Worker-0
2021-01-12 19:30:02 INFO: Performance scaling is enabled - attempting performance metrics capture
2021-01-12 19:30:02 INFO: The authentication account provided is in the correct format, continuing
2021-01-12 19:30:02 INFO: Starting performance measurement job for XA-Worker-01 using specified credentials
2021-01-12 19:30:02 INFO: CIM Connection test for XA-Worker-01 successful
2021-01-12 19:30:03 INFO: Starting performance measurement job for XA-Worker-02 using specified credentials
2021-01-12 19:30:03 INFO: CIM Connection test for XA-Worker-02 successful
2021-01-12 19:30:03 INFO: Starting performance measurement job for XA-Worker-03 using specified credentials
2021-01-12 19:30:03 INFO: CIM Connection test for XA-Worker-03 successful
2021-01-12 19:30:03 INFO: Starting performance measurement job for XA-Worker-04 using specified credentials
2021-01-12 19:30:03 INFO: CIM Connection test for XA-Worker-04 successful
2021-01-12 19:30:08 INFO: 1.5 - Overall CPU Average
2021-01-12 19:30:08 INFO: 17.5 - Overall Memory Average
2021-01-12 19:30:08 INFO: 120 - Overall Session Index Average
2021-01-12 19:30:08 INFO: 3 - Overall Session Count Average
2021-01-12 19:30:08 INFO: Start Circular Log Management
2021-01-12 19:30:08 INFO: It is currently outside working hours - performing machine analysis
2021-01-12 19:30:08 INFO: The current number of powered on machines is 4 and the target is 1 - resulting action is to Shutdown 3 machines
2021-01-12 19:30:08 INFO: Performance scaling is set to True and scaling outside of business hours is set to True
2021-01-12 19:30:08 INFO: Logging off all disconnected sessions
2021-01-12 19:30:08 INFO: Logging off all disconnected sessions in one hit
2021-01-12 19:30:08 INFO: Logging off userA
2021-01-12 19:30:08 INFO: User logoff mode is set to force, logging all users off of machines that are required to be shutdown
2021-01-12 19:30:08 INFO: Setting XA-Worker-02 maintenance mode On
2021-01-12 19:30:09 INFO: Found 1 user sessions on XA-Worker-02  
2021-01-12 19:30:09 INFO: Messaging all users on XA-Worker-02 to logoff
2021-01-12 19:30:09 INFO: Setting XA-Worker-03 maintenance mode On
2021-01-12 19:30:09 INFO: Found 3 user sessions on XA-Worker-03  
2021-01-12 19:30:09 INFO: Messaging all users on XA-Worker-03 to logoff
2021-01-12 19:30:09 INFO: Setting XA-Worker-04 maintenance mode On
2021-01-12 19:30:10 INFO: Found 4 user sessions on XA-Worker-04  
2021-01-12 19:30:10 INFO: Messaging all users on XA-Worker-04 to logoff
2021-01-12 19:30:11 INFO: Sending message to users to log off - 5 minute warning
2021-01-12 19:30:13 INFO: Sending message to users to log off - 5 minute warning
2021-01-12 19:30:16 INFO: Sending message to users to log off - 5 minute warning
2021-01-12 19:35:12 INFO: Sending message to users to log off - 5 minute warning
2021-01-12 19:35:14 INFO: Sending message to users to log off - 5 minute warning
2021-01-12 19:35:17 INFO: Sending message to users to log off - 5 minute warning
2021-01-12 19:40:12 INFO: Logging off all active user sessions after sending messages at 5 minutes and then 5 minutes
2021-01-12 19:40:13 INFO: Machine action for XA-Worker-02 - Shutdown immediately
2021-01-12 19:40:14 INFO: Logging off all active user sessions after sending messages at 5 minutes and then 5 minutes
2021-01-12 19:40:15 INFO: Machine action for XA-Worker-03 - Shutdown immediately
2021-01-12 19:40:17 INFO: Logging off all active user sessions after sending messages at 5 minutes and then 5 minutes
2021-01-12 19:40:17 INFO: Machine action for XA-Worker-04 - Shutdown immediately
2021-01-12 19:40:33 INFO: Setting XA-Worker-02 maintenance mode Off
2021-01-12 19:40:33 INFO: Setting XA-Worker-03 maintenance mode Off
2021-01-12 19:40:33 INFO: Setting XA-Worker-04 maintenance mode Off
2021-01-12 19:40:34 INFO: #######PowerScale script finishing#######
2021-01-12 19:40:34 INFO: -

Next run:

2021-01-12 19:46:28 INFO: -
2021-01-12 19:46:28 INFO: #######PowerScale script starting - Test mode value is False#######
2021-01-12 19:46:28 INFO: Getting a list of machine from dc01 based on prefix - XA-Worker-0
2021-01-12 19:46:29 INFO: Performance scaling is enabled - attempting performance metrics capture
2021-01-12 19:46:29 INFO: The authentication account provided is in the correct format, continuing
2021-01-12 19:46:29 INFO: Starting performance measurement job for XA-Worker-01 using specified credentials
2021-01-12 19:46:29 INFO: CIM Connection test for XA-Worker-01 successful
2021-01-12 19:46:34 INFO: 0 - Overall CPU Average
2021-01-12 19:46:34 INFO: 21 - Overall Memory Average
2021-01-12 19:46:34 INFO: 200 - Overall Session Index Average
2021-01-12 19:46:34 INFO: 5 - Overall Session Count Average
2021-01-12 19:46:34 INFO: Start Circular Log Management
2021-01-12 19:46:35 INFO: It is currently outside working hours - performing machine analysis
2021-01-12 19:46:35 INFO: The current number of powered on machines is 2 and the target is 1 - resulting action is to Shutdown 1 machines
2021-01-12 19:46:35 INFO: Performance scaling is set to True and scaling outside of business hours is set to True
2021-01-12 19:46:35 INFO: User logoff mode is set to force, logging all users off of machines that are required to be shutdown
2021-01-12 19:46:35 INFO: Setting XA-Worker-01 maintenance mode On
2021-01-12 19:46:35 INFO: Found 5 user sessions on XA-Worker-01 
2021-01-12 19:46:35 INFO: Messaging all users on XA-Worker-01 to logoff
2021-01-12 19:46:37 INFO: Sending message to users to log off - 5 minute warning
2021-01-12 20:00:02 INFO: -
2021-01-12 20:00:02 INFO: #######PowerScale script starting - Test mode value is False#######
2021-01-12 20:00:02 INFO: Getting a list of machine from dc01 based on prefix - XA-Worker-0
2021-01-12 20:00:02 INFO: Performance scaling is enabled - attempting performance metrics capture
2021-01-12 20:00:02 INFO: The authentication account provided is in the correct format, continuing
2021-01-12 20:00:02 INFO: Starting performance measurement job for XA-Worker-01 using specified credentials
2021-01-12 20:00:03 INFO: CIM Connection test for XA-Worker-01 successful
2021-01-12 20:00:08 INFO: 5 - Overall CPU Average
2021-01-12 20:00:08 INFO: 22 - Overall Memory Average
2021-01-12 20:00:08 INFO: 200 - Overall Session Index Average
2021-01-12 20:00:08 INFO: 5 - Overall Session Count Average
2021-01-12 20:00:08 INFO: Start Circular Log Management
2021-01-12 20:00:08 INFO: It is currently outside working hours - performing machine analysis
2021-01-12 20:00:08 INFO: The current number of powered on machines is 1 and the target is 1 - resulting action is to perform Scaling calculations
2021-01-12 20:00:08 INFO: Performance scaling is set to True and scaling outside of business hours is set to True
2021-01-12 20:00:08 INFO: Additional scaling is not enabled, the number of machines to scale at each run will be set to the default of 1
2021-01-12 20:00:08 INFO: The current running machines matches the target machines number, performing scaling analysis
2021-01-12 20:00:08 INFO: Scaling has been selected, the current scaling metric is Session and there are 7 machines currently powered off and there are 0 in maintenance mode available.
2021-01-12 20:00:08 INFO: Working with poweredOffMachines this round - maintenance machines will always be selected first
2021-01-12 20:00:08 INFO: Machine selected to be placed into service is XA-Worker-02 the machine is powered Off and maintename mode is False
2021-01-12 20:00:08 INFO: We're out of hours with the correct number of machines - removing scaling tag from XA-Worker-05
2021-01-12 20:00:09 INFO: #######PowerScale script finishing#######
2021-01-12 20:00:09 INFO: -

Can you help? Thanks!

**Comment by leeej84** [comment] 2021-01-13 09:51
No problems. If you take the latest release of the script, I believe this issue is already solved.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by Wausert** [comment] 2021-01-13 10:11
Hi Leee,

Thanks for the quick reply. I will try with the latest version and see what happens.
I'm having this issue with the version I downloaded on the 15th of December 2020.

All the best,

Wausert

**Comment by leeej84** [comment] 2021-01-13 10:21
I checked in the latest release on the 17th December. It was a very similar issue.

Let me know how you get on.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by Wausert** [comment] 2021-01-19 19:53
Today I noticed the problem again. XA-Worker-05 was turned on during the day because the session threshold was reached automatically powering up this machine. Around 3 PM PowerScale put the machine into maintenance mode but there were active users on there (not forcing them to logoff).

However around 20:00 the machine was still in maintenance mode and no users were logged on anymore.
All machines where shutdown (forcing users to logoff) Also XA-Worker-03 which had the most active users was shutdown.  
Next Powerscale run, no machines where available because of this resulting in taking machine XA-Worker-05 out of maintenance resulting no one is logged in anymore...

2021-01-19 19:30:02 INFO: -
2021-01-19 19:30:02 INFO: #######PowerScale script starting - Test mode value is False#######
2021-01-19 19:30:02 INFO: Getting a list of machine from dc01  based on prefix - XA-Worker-0
2021-01-19 19:30:02 INFO: Performance scaling is enabled - attempting performance metrics capture
2021-01-19 19:30:02 INFO: The authentication account provided is in the correct format, continuing
2021-01-19 19:30:03 INFO: Starting performance measurement job for XA-Worker-01 using specified credentials
2021-01-19 19:30:03 INFO: CIM Connection test for XA-Worker-01  successful
2021-01-19 19:30:03 INFO: Starting performance measurement job for XA-Worker-02 using specified credentials
2021-01-19 19:30:03 INFO: CIM Connection test for XA-Worker-02.  successful
2021-01-19 19:30:03 INFO: Starting performance measurement job for XA-Worker-03 using specified credentials
2021-01-19 19:30:03 INFO: CIM Connection test for XA-Worker-03.  successful
2021-01-19 19:30:03 INFO: Starting performance measurement job for XA-Worker-04  using specified credentials
2021-01-19 19:30:03 INFO: CIM Connection test for XA-Worker-04.  successful
2021-01-19 19:30:08 INFO: 1.5 - Overall CPU Average
2021-01-19 19:30:08 INFO: 17.5 - Overall Memory Average
2021-01-19 19:30:08 INFO: 90 - Overall Session Index Average
2021-01-19 19:30:08 INFO: 2.25 - Overall Session Count Average
2021-01-19 19:30:08 INFO: Start Circular Log Management
2021-01-19 19:30:08 INFO: It is currently outside working hours - performing machine analysis
2021-01-19 19:30:08 INFO: The current number of powered on machines is 4 and the target is 1 - resulting action is to Shutdown 3 machines
2021-01-19 19:30:08 INFO: Performance scaling is set to True and scaling outside of business hours is set to True
2021-01-19 19:30:08 INFO: Logging off all disconnected sessions
2021-01-19 19:30:08 INFO: Logging off all disconnected sessions in one hit
2021-01-19 19:30:08 INFO: Logging off  USERA
2021-01-19 19:30:08 INFO: User logoff mode is set to force, logging all users off of machines that are required to be shutdown
2021-01-19 19:30:09 INFO: Setting XA-Worker-04.  maintenance mode On
2021-01-19 19:30:09 INFO: Found 1 user sessions on XA-Worker-04. 
2021-01-19 19:30:09 INFO: Messaging all users on  XA-Worker-04 to logoff
2021-01-19 19:30:09 INFO: Setting XA-Worker-01.  maintenance mode On
2021-01-19 19:30:09 INFO: Found 2 user sessions on XA-Worker-01. 
2021-01-19 19:30:09 INFO: Messaging all users on  XA-Worker-01 to logoff
2021-01-19 19:30:10 INFO: Setting XA-Worker-02.  maintenance mode On
2021-01-19 19:30:10 INFO: Found 3 user sessions on XA-Worker-02. 
2021-01-19 19:30:10 INFO: Messaging all users on  XA-Worker-02 to logoff
2021-01-19 19:30:11 INFO: Sending message to users to log off - 5 minute warning
2021-01-19 19:30:11 INFO: Sending message to users to log off - 5 minute warning
2021-01-19 19:30:17 INFO: Sending message to users to log off - 5 minute warning
2021-01-19 19:35:12 INFO: Sending message to users to log off - 5 minute warning
2021-01-19 19:35:12 INFO: Sending message to users to log off - 5 minute warning
2021-01-19 19:35:17 INFO: Sending message to users to log off - 5 minute warning
2021-01-19 19:40:12 INFO: Logging off all active user sessions after sending messages at 5 minutes and then 5 minutes
2021-01-19 19:40:12 INFO: Machine action for  XA-Worker-04 - Shutdown immediately
2021-01-19 19:40:12 INFO: Logging off all active user sessions after sending messages at 5 minutes and then 5 minutes
2021-01-19 19:40:12 INFO: Machine action for  XA-Worker-01 - Shutdown immediately
2021-01-19 19:40:17 INFO: Logging off all active user sessions after sending messages at 5 minutes and then 5 minutes
2021-01-19 19:40:18 INFO: Machine action for  XA-Worker-02 - Shutdown immediately
2021-01-19 19:40:32 INFO: Setting XA-Worker-04.  maintenance mode Off
2021-01-19 19:40:33 INFO: Setting XA-Worker-01.  maintenance mode Off
2021-01-19 19:40:33 INFO: Setting XA-Worker-02.  maintenance mode Off
2021-01-19 19:40:33 INFO: #######PowerScale script finishing#######
2021-01-19 19:40:33 INFO: -

2021-01-19 20:00:02 INFO: #######PowerScale script starting - Test mode value is False#######
2021-01-19 20:00:02 INFO: Getting a list of machine from dc01 based on prefix - XA-Worker-0
2021-01-19 20:00:03 INFO: Performance scaling is enabled - attempting performance metrics capture
2021-01-19 20:00:03 INFO: The authentication account provided is in the correct format, continuing
2021-01-19 20:00:03 INFO: Starting performance measurement job for XA-Worker-03 using specified credentials
2021-01-19 20:00:03 INFO: CIM Connection test for XA-Worker-03 successful
2021-01-19 20:00:08 INFO: 17 - Overall CPU Average
2021-01-19 20:00:08 INFO: 21 - Overall Memory Average
2021-01-19 20:00:08 INFO: 200 - Overall Session Index Average
2021-01-19 20:00:08 INFO: 5 - Overall Session Count Average
2021-01-19 20:00:08 INFO: Start Circular Log Management
2021-01-19 20:00:08 INFO: It is currently outside working hours - performing machine analysis
2021-01-19 20:00:08 INFO: The current number of powered on machines is 2 and the target is 1 - resulting action is to Shutdown 1 machines
2021-01-19 20:00:08 INFO: Performance scaling is set to True and scaling outside of business hours is set to True
2021-01-19 20:00:08 INFO: User logoff mode is set to force, logging all users off of machines that are required to be shutdown
2021-01-19 20:00:08 INFO: Setting XA-Worker-03 maintenance mode On
2021-01-19 20:00:08 INFO: Found 5 user sessions on XA-Worker-03
2021-01-19 20:00:08 INFO: Messaging all users on XA-Worker-03 to logoff
2021-01-19 20:00:11 INFO: Sending message to users to log off - 5 minute warning
2021-01-19 20:05:11 INFO: Sending message to users to log off - 5 minute warning
2021-01-19 20:10:11 INFO: Logging off all active user sessions after sending messages at 5 minutes and then 5 minutes
2021-01-19 20:10:12 INFO: Machine action for XA-Worker-03 - Shutdown immediately
2021-01-19 20:10:29 INFO: Setting XA-Worker-03 maintenance mode Off
2021-01-19 20:10:30 INFO: #######PowerScale script finishing#######
2021-01-19 20:10:30 INFO: -

2021-01-19 20:30:02 INFO: #######PowerScale script starting - Test mode value is False#######
2021-01-19 20:30:02 INFO: Getting a list of machine from dc01 based on prefix - XA-Worker-0
2021-01-19 20:30:03 INFO: Performance scaling is enabled - attempting performance metrics capture
2021-01-19 20:30:03 INFO: There are no machines powered on and available to collect performance metrics from, skipping performance collection
2021-01-19 20:30:03 INFO: Start Circular Log Management
2021-01-19 20:30:03 INFO: It is currently outside working hours - performing machine analysis
2021-01-19 20:30:03 INFO: The current number of powered on machines is 0 and the target is 1 - resulting action is to Startup 1 machines
2021-01-19 20:30:03 INFO: Performance scaling is set to True and scaling outside of business hours is set to True
2021-01-19 20:30:03 INFO: It is currently inside working hours, machines are required to be started
2021-01-19 20:30:03 INFO: There are 0 machine(s) currently switched on and registered, There are 1 machine(s) in maintenance mode and there are 7 machine(s) powered off
2021-01-19 20:30:03 INFO: In total there are 8 machine(s) able to be placed into service.
2021-01-19 20:30:03 INFO: The number of machines available is 8 and the number required is 1
2021-01-19 20:30:03 INFO: The number of machines in maintenance mode is 1 and the number of machine(s) needed is 1
2021-01-19 20:30:03 INFO: There are sufficient machines in maintenance mode to service the request
2021-01-19 20:30:03 INFO: Taking XA-Worker-05 out of maintenance mode
2021-01-19 20:30:03 INFO: No performance information was collected, skipping Dashboard update
2021-01-19 20:30:03 INFO: #######PowerScale script finishing#######
2021-01-19 20:30:03 INFO: -

**Comment by leeej84** [comment] 2021-01-20 10:14
Can you please ping me your config and full log file, I’ll reproduce your configuration in my lab and see if I can pinpoint the issue.

It looks like its shutting down the wrong machine and is instead shutting down a live production server rather than the scaled on one right?

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by Wausert** [comment] 2021-01-20 19:22
Hi Leee,

Thanks, I've sent you an email.

Best regards,

Wausert

**Comment by leeej84** [comment] 2021-01-22 13:08
Hi Wausert

Please take the main branch for me. I've added a new parameter in the Create Config.ps1

PersistScaled

Set this to false for me. This should force the scaled on machine to shutdown as soon as it sees it empty. Please bear in mind that if you script runs regularly it may shut the machine down before users can logon to it. In this scenario you may find yourself having machines spun up and shutdown regularly.

Please let me know how you get on though.

**Comment by Wausert** [comment] 2021-01-22 15:57
Hi Leee,

Thanks, I will give it a try and let you know.

Does this also fix the problem that a machine in maintenance mode is not visible the first time the script runs after business hours?

Thanks again!

Wouter

**Comment by leeej84** [comment] 2021-01-22 16:05
Yes actually it should. The reason it's not visible is because it's scaled on.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by Wausert** [comment] 2021-01-22 19:05
Hi Leee,

I’ve setup the new version. I will let you know how it runs.

2 minor details, there are some typos in the output message:

It is caurrently outside working hours - performing machine anlysis

All the best

**Comment by alexis-roger** [comment] 2021-01-26 11:17
Hi,

I'm evaluating the tool and it looks like I have a similar issue. When using performance scaling based on Index for example, machines that were scaled on but that have 0 sessions and are in maintenance mode are not performance evaluated (no cim session). When I manually remove maintenance mode on the machine, the machine is powered down as it should.

**Comment by leeej84** [comment] 2021-01-26 11:54
Take the latest branch. You have had the same issue where a machine is scaled on and left in maintenance mode.


Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by alexis-roger** [comment] 2021-01-26 14:51
Thanks Leee, I was already using the latest branch code. I downloaded again to be sure but issue is the same.
Right now I have:
- 1 machine OFF and maintenance mode OFF with 0 session (VDA01)
- 1 machine ON and maintenance mode ON with 0 session (VDA03 - Load index 0)
- 1 machine ON and maintenance mode OFF with 3 sessions (VDA01 - load index 6000)

Load Index threshold is 7000 but the script is not turning off the VDA03 machine... maybe I'm missing something.
When running the script, it's only evaluating the machine that is ON and not in maintenance MODE:

VERBOSE: #######PowerScale script starting - Test mode value is True#######
VERBOSE: Getting a list of machine from citrix.lab.local based on prefix - VDA
VERBOSE: There are 2 scaled on machine, these will be shutdown as soon as they are empty of users in business hours.
VERBOSE: Performance scaling is enabled - attempting performance metrics capture
VERBOSE: The authentication account provided is in the correct format, continuing
VERBOSE: Starting performance measurement job for VDA02.lab.local using specified credentials
VERBOSE: CIM Connection test for VDA02.lab.local successful
VERBOSE: ThreadID: Beginning 18456
VERBOSE: 0 - Overall CPU Average
VERBOSE: 53 - Overall Memory Average
VERBOSE: 6000 - Overall Session Index Average
VERBOSE: 3 - Overall Session Count Average
VERBOSE: Start Circular Log Management
VERBOSE: The current number of powered on machines is 1 and the target is 1 - resulting action is to perform Scaling
calculations
VERBOSE: It is currently inside working hours - performing machine analysis
VERBOSE: Additional scaling is not enabled, the number of machines to scale at each run will be set to the default of 1
VERBOSE: The current running machines matches the target machines number, performing scaling analysis
VERBOSE: Scaling has been selected, the current scaling metric is Index and there are 1 machines currently powered off
and there are 1 in maintenance mode available.
VERBOSE: Working with maintenanceMachines this round - maintenance machines will always be selected first
VERBOSE: Machine selected to be placed into service is VDA03.lab.local the machine is powered On and maintename mode is
 True

**Comment by leeej84** [comment] 2021-01-26 15:20
Okay, so. Both your machines here have scaled-on tags.

In the latest branch I added an option to $persistScaled

Can you recreate your config, using the latest create-config file and set persistScaled to false.

Let me know your outcome after doing this.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by alexis-roger** [comment] 2021-01-26 15:24
$persistScaled is already set to $false as it is by default in the latest script version...

**Comment by leeej84** [comment] 2021-01-26 16:19
I will replicate it in the lab, perhaps this is a different issue.

What the script does is add the scaled machines to the in hours machine. That’s the issue, but…. persistScaled being false should mean that these machines are targeted as normal.

Leave it with me.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by Wausert** [comment] 2021-01-26 19:21
Hi Leee,

I've tested the new version but unfortunately the bug is still in there.
For example, when business hours ended, the next run- but also in consecutive run's- the machine in maintenance mode is ignored, thus Powerscale signals an active machine and its users to logoff and continues to shutdown the machine leaving no machines powered on or in maintenance mode.... I even spins up a new machine because it will fail to see the machine that is on and in maintenance mode.

persistScaled is false in my config.

Best regards,

Wouter

**Comment by leeej84** [comment] 2021-01-27 16:25
Hi

I’m running through this now.


  *   1 machine OFF and maintenance mode OFF (XDSHNP-01)
  *   1 machine ON and maintenance mode ON with 0 sessions (XDSHNP-02)
  *   1 machine ON and maintenance mode OFF with 1 session (XDSHNP-03)
  *   Inside working hours

I’m running through this in the lab now. I notice two of your machines are scaled on also so I’ve replicated that.

I did get an issue initially. I’ve fixed a typo in my code. The scaled machines were not being picked up correctly. They are now.

The scaling threshold is only used when the machine are being scaled up, not down. If you mean, why is the machine not being scaled on. Its because the load index is an average of all machines in the farm.

If you check you powerscale folder you will find a Dashboard folder, this will have graphics that list out those performance metrics.

If this is your issue you need to open a separate thread. Its not the same issue.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by alexis-roger** [comment] 2021-01-28 10:19
Hi Leee, thanks for taking the time.

It seems the script is not taking into account the average Index but only the index of VDA02 that is Powered ON and out of maintenance mode.

If I manually take VDA03 out of maintenance mode, VDA02 AND VDA03 metrics are calculated, then the script correctly shut down VDA03:

VERBOSE: -
VERBOSE: #######PowerScale script starting - Test mode value is False#######
VERBOSE: Getting a list of machine from citrix.lab.local based on prefix - VDA
VERBOSE: There are 2 scaled on machines, these will be shutdown as soon as they are empty of users in business hours.
VERBOSE: Performance scaling is enabled - attempting performance metrics capture
VERBOSE: The authentication account provided is in the correct format, continuing
VERBOSE: Starting performance measurement job for VDA02.lab.local using specified credentials
VERBOSE: CIM Connection test for VDA02.lab.local successful
VERBOSE: ThreadID: Beginning 18456
**VERBOSE: Starting performance measurement job for VDA03.lab.local using specified credentials
VERBOSE: CIM Connection test for VDA03.lab.local successful**
VERBOSE: ThreadID: Beginning 18456
VERBOSE: 1 - Overall CPU Average
VERBOSE: 44.5 - Overall Memory Average
VERBOSE: **3000 - Overall Session Index Average**
VERBOSE: 1.5 - Overall Session Count Average
VERBOSE: Start Circular Log Management
VERBOSE: The current number of powered on machines is 2 and the target is 1 - resulting action is to Shutdown 1
machines
VERBOSE: It is currently inside working hours - performing machine analysis
VERBOSE: User logoff mode is not set to force, waiting for sessions to gracefully disconnect before powering machines
down
VERBOSE: No active session found on VDA03.lab.local, performing shutdown
VERBOSE: Machine action for lab\VDA03 - Shutdown immediately

**Comment by leeej84** [comment] 2021-01-28 11:26
@alexis-roger - I have created a new issue for your problems as they are not the same as the ones in this issue.

**Comment by leeej84** [comment] 2021-03-01 10:20
Confirmed as fixed.

**Closed by leeej84** 2021-03-01 10:20 UTC
